development:
  adapter: postgresql
  database: stories_devise_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: stories_devise_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: stories_devise_production
  pool: 5
  timeout: 5000
